# Site Information
license:          "MIT"
license-url:      "https://github.com/BlackrockDigital/startbootstrap/blob/gh-pages/LICENSE"
author:           "Blackrock Digital"

# Site Settings
baseurl:          ""

source: "website"
destination: "website/_content"

# Build settings
exclude:          [node_modules]

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative-permalinks: true

# Gems
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
  - rouge

# Collections
collections:
  premium:
    output: false
  templates:
    output: true
    permalink: /template-overviews/:title/

# Pagination
paginate: 5
paginate_path: "/articles/page:num/"